muppets1.domain:
  # notify others
  notify:
    - piggy@muppets.domain
  # override ignored mounts
  ignored:
    - /tmp
  # override thresholds
  thresholds:
    default:
      warning: 80
      notice: 70
      info: 60
    /srv:
      warning: 50
muppets2.domain:
  # override ignored mounts
  # leave empty to ignore none
  ignored: {}