dirs:
  # directory where log files are kept
  log: "/home/kermit/sauron2.d/logs"
  # directory where tmp files are kept
  tmp: "/home/kermit/sauron2.d/tmp"
# send mail
email:
  enabled: true
  services: true
  server: smtp.vub.ac.be
# mounts which are ignored
# leave empty to ignore none
ignored:
  - /var
  - /tmp
notify:
  - kermit@muppets.domain
ssh_timeout: 15
thresholds:
  default:
    critical: 97
    warning: 94
    notice: 90
    info: 87
  # set specific thresholds
  /:
    info: 50
